export const ENDPOINTS = {
    LOGIN: `/users/login`,
    SIGNUP: `/users/create`,
    VERIFY_EMAIL: '/users/verify-email',
    VERIFY_CODE: '/users/verify-otp',
    RESET_PASSWORD: '/users/reset-password/',
    EXPERIENCE_LEVEL: '/experience-level',
    FITNESS_GOAL: '/fitness-goal',
    SOCIAL_PREFERENCES: '/social-preference',
    RUNNING_TIME: '/running-time',
    SOCIAL_LINKS: '/social-link?user_id=',
    CATEGORY: "/category",
    CREATE_SOCIAL_LINK: "/social-link/create",
    CREATE_GOALS: "/fitness-goal/create",
    CREATE_CLUB_GOALS: "/club-goals/create",
    CREATE_ROUTE: "/routes/create",
    CREATE_CLUB: "/clubs/create",
    UPDATE_CLUB: "/clubs/",
    CREATE_CLUB_RULES: "/club-rules/create",
    CREATE_SCHEDULE: "/schedule/create",
    DELETE_SCHEDULE:"/schedule/",
    PAYMENT_INTENT: "/payments/create-intent",
    FOLLOW_USER: "/users/",
    ADD_REVIEW: "/reviews/create",
    CREATE_POST: "/posts/create",
    UPDATE_CLUB_POST: "/posts/",
    CREATE_HIGHLIGHT: "/highlights/create",
    UPDATE_HIGHLIGHT: "/highlights/",
    GET_REVIEWS: "/reviews?",
    CREATE_EVENT: "/events/create",
    UPDATE_EVENT: "/events/",
    CREATE_MEETING_POINTS: "/meeting-points/create",
    DELETE_MEETING_POINTS: "/meeting-points/",
    SEND_INVITATION: "/events/send-invite",
    GET_FOLLOWERS: "/users/followers/list?",
    EVENT_ACTIVITY_CREATE: "/event-activities/create",
    CREATE_BADGE: "/badges/create",
    DELETE_BADGE: "/badges/",
    CREATE_ACHIEVEMENT: "/achievements/create",
    DELETE_ACHIEVEMENT: "/achievements/",
    UPDATE_ACHIEVEMENT: "/achievements/",
    GET_ACHIEVEMENT: "/achievements/"

};